package com.zh.ch.bigdata.springboot.manager.mysql.dao;

import com.zh.ch.bigdata.springboot.manager.mysql.bean.DataPrimarykeyChangedRecord;
import com.zh.ch.bigdata.springboot.manager.mysql.bean.DataPrimarykeyChangedRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DataPrimarykeyChangedRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_primarykey_changed_record
     *
     * @mbggenerated
     */
    int countByExample(DataPrimarykeyChangedRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_primarykey_changed_record
     *
     * @mbggenerated
     */
    int deleteByExample(DataPrimarykeyChangedRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_primarykey_changed_record
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long changeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_primarykey_changed_record
     *
     * @mbggenerated
     */
    int insert(DataPrimarykeyChangedRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_primarykey_changed_record
     *
     * @mbggenerated
     */
    int insertSelective(DataPrimarykeyChangedRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_primarykey_changed_record
     *
     * @mbggenerated
     */
    List<DataPrimarykeyChangedRecord> selectByExample(DataPrimarykeyChangedRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_primarykey_changed_record
     *
     * @mbggenerated
     */
    DataPrimarykeyChangedRecord selectByPrimaryKey(Long changeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_primarykey_changed_record
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") DataPrimarykeyChangedRecord record, @Param("example") DataPrimarykeyChangedRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_primarykey_changed_record
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") DataPrimarykeyChangedRecord record, @Param("example") DataPrimarykeyChangedRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_primarykey_changed_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DataPrimarykeyChangedRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_primarykey_changed_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DataPrimarykeyChangedRecord record);
}